### ISSUE TITLE
Trip Details/AirSegment by PNR number & Last Date

### ISSUE THREAD

**Issue by kaviuniyal** [Travelport/travelport-uapi-tutorial-c-sharp#197] opened 2019-08-27 11:37 UTC
Hi Team , 

how i can fetch the trip details from the PNR number & Last Name

Currently we just use the LowFareSearch to find the price for our package & then we book the ticket by other Tool , now we just have the PNR Number & Last Name, from our booker we just got this info : https://viewtrip.travelport.com/#!/itinerary?loc=XXXX&lName=XXXXX

Now i want to retrieve the trip information from Universal API by using the PNR Number & Last Name so we can have the trip details in our database and can alert our customer if there is any changes

Thanks

**Comment by vivekjyotipramanik** [comment] 2019-08-27 16:50
Duplicate of https://github.com/Travelport/travelport-uapi-tutorial/issues/687

**Closed as completed by vivekjyotipramanik** 2019-08-27 16:50 UTC
